"""Unit tests for ``alliman doctor`` — pure filesystem inspection over a tmp install tree."""

from __future__ import annotations

from pathlib import Path

import pytest

from alliman.doctor import _DEFAULT_SKILLS, format_doctor_report, run_doctor

VENDORED_SOURCE = "/nix/store/abc-allium"


def _build_install(
    root: Path,
    *,
    skills: list[str] | None = None,
    with_manifest: bool = True,
    with_entrypoint: bool = True,
    with_prompts: bool = True,
    vendored_source: str = VENDORED_SOURCE,
) -> None:
    """Build a (configurable) Allium install tree under *root* matching the installer's layout."""
    skills = _DEFAULT_SKILLS if skills is None else skills
    skills_root = root / ".agents/skills"
    skills_root.mkdir(parents=True, exist_ok=True)

    for skill in skills:
        sk = skills_root / skill
        sk.mkdir(parents=True, exist_ok=True)
        (sk / "SKILL.md").write_text(f"# {skill}\n")

    if with_entrypoint:
        entry = skills_root / "allium-entrypoint"
        entry.mkdir(parents=True, exist_ok=True)
        (entry / "SKILL.md").write_text("# allium-entrypoint\n")

    if with_manifest:
        (skills_root / ".allium-devenv-source").write_text(
            "Generated by allium-install-codex-skills.\n"
            f"Vendored Allium source: {vendored_source}\n"
        )

    if with_prompts:
        prompts_root = root / ".agents/prompts"
        prompts_root.mkdir(parents=True, exist_ok=True)
        (prompts_root / "allium-01.md").write_text("# prompt\n")


@pytest.fixture
def env(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin the ALLIUM_* env the doctor reads to the installer's defaults."""
    monkeypatch.setenv("DEVENV_ROOT", "/tmp/fake-devenv")
    monkeypatch.setenv("ALLIUM_CODEX_SKILLS_DIR", ".agents/skills")
    monkeypatch.setenv("ALLIUM_CODEX_PROMPTS_DIR", ".agents/prompts")
    monkeypatch.setenv("ALLIUM_SHELL_SKILL_LIST", " ".join(_DEFAULT_SKILLS))
    monkeypatch.setenv("ALLIUM_EXPECTED_VENDORED_SOURCE", VENDORED_SOURCE)
    monkeypatch.setenv("ALLIUM_PROMPTS_ENABLED", "1")


def test_healthy_tree_passes(tmp_path: Path, env: None) -> None:
    _build_install(tmp_path)
    report = run_doctor(tmp_path)
    assert report.ok, format_doctor_report(report)


def test_missing_manifest_fails(tmp_path: Path, env: None) -> None:
    _build_install(tmp_path, with_manifest=False)
    report = run_doctor(tmp_path)
    assert not report.ok
    failed = {c.name for c in report.checks if not c.ok}
    assert "install manifest" in failed
    # vendored-source check also fails because the manifest text is empty
    assert "manifest: vendored source" in failed


def test_partial_install_missing_skill_fails(tmp_path: Path, env: None) -> None:
    """A missing skill dir must be flagged even though the manifest + entrypoint are present."""
    _build_install(tmp_path, skills=[s for s in _DEFAULT_SKILLS if s != "weed"])
    report = run_doctor(tmp_path)
    assert not report.ok
    failed = {c.name for c in report.checks if not c.ok}
    assert failed == {"skill: weed"}


def test_missing_entrypoint_fails(tmp_path: Path, env: None) -> None:
    _build_install(tmp_path, with_entrypoint=False)
    report = run_doctor(tmp_path)
    assert not report.ok
    assert any(c.name == "skill: allium-entrypoint" and not c.ok for c in report.checks)


def test_stale_vendored_source_fails(tmp_path: Path, env: None) -> None:
    _build_install(tmp_path, vendored_source="/nix/store/OLD-allium")
    report = run_doctor(tmp_path)
    assert not report.ok
    assert any(c.name == "manifest: vendored source" and not c.ok for c in report.checks)


def test_missing_prompts_fails_when_enabled(tmp_path: Path, env: None) -> None:
    _build_install(tmp_path, with_prompts=False)
    report = run_doctor(tmp_path)
    assert not report.ok
    assert any(c.name == "prompts installed" and not c.ok for c in report.checks)


def test_prompts_skipped_when_disabled(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, env: None) -> None:
    monkeypatch.setenv("ALLIUM_PROMPTS_ENABLED", "0")
    _build_install(tmp_path, with_prompts=False)
    report = run_doctor(tmp_path)
    assert report.ok, format_doctor_report(report)
    assert not any(c.name == "prompts installed" for c in report.checks)


def test_custom_skill_list_is_honored(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, env: None) -> None:
    monkeypatch.setenv("ALLIUM_SHELL_SKILL_LIST", "allium weed")
    _build_install(tmp_path, skills=["allium", "weed"])
    report = run_doctor(tmp_path)
    assert report.ok, format_doctor_report(report)
    skill_checks = {
        c.name
        for c in report.checks
        if c.name.startswith("skill: ") and c.name != "skill: allium-entrypoint"
    }
    assert skill_checks == {"skill: allium", "skill: weed"}


def test_no_devenv_root_is_flagged(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, env: None) -> None:
    monkeypatch.delenv("DEVENV_ROOT", raising=False)
    _build_install(tmp_path)
    report = run_doctor(tmp_path)
    assert any(c.name == "devenv shell" and not c.ok for c in report.checks)


def test_format_report_marks_fail_lines(tmp_path: Path, env: None) -> None:
    _build_install(tmp_path, with_manifest=False)
    text = format_doctor_report(run_doctor(tmp_path))
    assert "FAIL install manifest" in text
    assert "OK   skill: allium" in text
