#!/usr/bin/env bash
set -euo pipefail

require_env() {
  var_name="$1"
  if [ -z "${!var_name:-}" ]; then
    echo "Error: required environment variable $var_name is not set." >&2
    exit 1
  fi
}

resolve_target_root() {
  target_dir="$1"
  case "$target_dir" in
    /*)
      printf '%s\n' "$target_dir"
      ;;
    *)
      printf '%s/%s\n' "$repo_root" "$target_dir"
      ;;
  esac
}

require_env ALLIUM_SOURCE
require_env ALLIUM_SKILLS_DIR
require_env ALLIUM_CLI_SKILLS_DIR
require_env ALLIUM_ENTRYPOINT_SOURCE
require_env ALLIUM_SPECS_DIR
require_env ALLIUM_CODEX_SKILLS_DIR
require_env ALLIUM_SHELL_SKILL_LIST
require_env ALLIUM_PROMPTS_ENABLED

if [ "$ALLIUM_PROMPTS_ENABLED" = "1" ]; then
  require_env ALLIUM_PROMPTS_DIR
  require_env ALLIUM_CODEX_PROMPTS_DIR
fi

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "Error: run this from inside a Git repository." >&2
  exit 1
fi

repo_root="$(git rev-parse --show-toplevel)"
target_root="$(resolve_target_root "$ALLIUM_CODEX_SKILLS_DIR")"
mkdir -p "$target_root"

echo "Installing Allium skills"
echo "Vendored source: $ALLIUM_SKILLS_DIR"
echo "Local source: $ALLIUM_CLI_SKILLS_DIR"
echo "Target: $target_root"
echo

install_skill_dir() {
  source_path="$1"
  target_path="$2"
  tmp_path="$target_root/.tmp-$(basename "$target_path")"

  if [ ! -f "$source_path/SKILL.md" ]; then
    echo "Error: expected $source_path/SKILL.md to exist." >&2
    exit 1
  fi

  rm -rf "$tmp_path"
  cp -R "$source_path" "$tmp_path"
  chmod -R u+w "$tmp_path"

  rm -rf "$target_path"
  mv "$tmp_path" "$target_path"

  echo "Installed $target_path"
}

for skill in $ALLIUM_SHELL_SKILL_LIST; do
  source_path="$ALLIUM_SKILLS_DIR/$skill"
  target_path="$target_root/$skill"
  install_skill_dir "$source_path" "$target_path"
done

found_local_cli_skill=0
for source_path in "$ALLIUM_CLI_SKILLS_DIR"/*; do
  if [ ! -d "$source_path" ]; then
    continue
  fi

  if [ ! -f "$source_path/SKILL.md" ]; then
    continue
  fi

  found_local_cli_skill=1
  skill_name="$(basename "$source_path")"
  install_skill_dir "$source_path" "$target_root/$skill_name"
done

if [ "$found_local_cli_skill" -eq 0 ]; then
  echo "Error: expected at least one skill directory with SKILL.md in $ALLIUM_CLI_SKILLS_DIR." >&2
  exit 1
fi

# Install entrypoint skill with specsDir baked in via Jinja2
entrypoint_target="$target_root/allium-entrypoint"
entrypoint_tmp="$target_root/.tmp-allium-entrypoint"
rm -rf "$entrypoint_tmp"
cp -R "$ALLIUM_ENTRYPOINT_SOURCE" "$entrypoint_tmp"
chmod -R u+w "$entrypoint_tmp"
minijinja-cli "$entrypoint_tmp/SKILL.md" -Dspecs_dir="$ALLIUM_SPECS_DIR" -o "$entrypoint_tmp/SKILL.md"
rm -rf "$entrypoint_target"
mv "$entrypoint_tmp" "$entrypoint_target"
echo "Installed $entrypoint_target (specsDir=$ALLIUM_SPECS_DIR)"

if [ "$ALLIUM_PROMPTS_ENABLED" = "1" ]; then
  prompts_target_root="$(resolve_target_root "$ALLIUM_CODEX_PROMPTS_DIR")"

  if [ "$prompts_target_root" = "$target_root" ]; then
    echo "Error: prompts target directory must be different from skills target directory." >&2
    exit 1
  fi

  if [ ! -d "$ALLIUM_PROMPTS_DIR" ]; then
    echo "Error: expected prompts source directory at $ALLIUM_PROMPTS_DIR." >&2
    exit 1
  fi

  mkdir -p "$(dirname "$prompts_target_root")"
  prompts_tmp="$(dirname "$prompts_target_root")/.tmp-$(basename "$prompts_target_root")"
  rm -rf "$prompts_tmp"
  cp -R "$ALLIUM_PROMPTS_DIR" "$prompts_tmp"
  chmod -R u+w "$prompts_tmp"

  found_prompt_file=0
  for prompt_file in "$prompts_tmp"/*.md; do
    if [ -f "$prompt_file" ]; then
      found_prompt_file=1
      break
    fi
  done

  if [ "$found_prompt_file" -eq 0 ]; then
    echo "Error: expected at least one markdown prompt file in $ALLIUM_PROMPTS_DIR." >&2
    exit 1
  fi

  rm -rf "$prompts_target_root"
  mv "$prompts_tmp" "$prompts_target_root"
  echo "Installed $prompts_target_root"
fi

{
  echo "Generated by allium-install-codex-skills."
  echo "Source module: devenv-allium"
  echo "Vendored Allium source: $ALLIUM_SOURCE"
  echo "Local Allium CLI skills source: $ALLIUM_CLI_SKILLS_DIR"
  if [ "$ALLIUM_PROMPTS_ENABLED" = "1" ]; then
    echo "Local Allium prompts source: $ALLIUM_PROMPTS_DIR"
  fi
  echo
  echo "Do not edit these generated copies directly."
  echo "Update the shared devenv-allium repo, then rerun allium-install-codex-skills."
} > "$target_root/.allium-devenv-source"

echo
echo "Allium install complete."
echo
if [ "$ALLIUM_PROMPTS_ENABLED" = "1" ]; then
  echo "If another editor reads from different skill or prompt directories, symlink from $target_root and $ALLIUM_CODEX_PROMPTS_DIR."
else
  echo "If another editor reads skills from a different directory, symlink from $target_root."
fi
